### ISSUE TITLE
Add playlist 0

### ISSUE THREAD

**Issue by Zod-** [trew/RankTracker#1]
It seems that they don't use the ranked points when doing unranked matches but rather have a seperate hidden ranking for that. So all the `RankPoints: .. Playlist=0` refer to those unranked matches. Also I guess I wasted today by making this https://i.imgur.com/M1TDfPj.png

**Comment by Zod-** [comment]
More info because of your reddit post:

It's true that the specific `PlaylistID` appears when searching for a game. However they only have 1 rank for all 4 of the normal playlists. Instead of having a rank for each playlist like on the ranked modes. It doesn't have to be as accurate as the ranked mode so they add it all together into one rank so they can do basic matchmaking.

Some data [here](https://gist.githubusercontent.com/Zod-/8364659dd3459d147cce/raw/41971d7940383c2dde7afd38bd8cb1a8a9626846/launch.log)

As you can see rank gets added to playlist 0 when playing either 2v2 or 3v3 in normal mode. (There is only join because we did several matches in a row without leaving)

**Comment by trew** [comment]
I think you are misunderstanding how the rank points and unranked playlists works. The rank points for unranked list are not used for matchmaking. There are other values(Mu and Sigma) that dictates the matchmaking. I have no idea why they even have rank points for the unranked lists in the logs. I just don't see the point in including a stat that bunches up 1v1,2v2,3v3 and 4v4 into a single stat. If unranked were to be included, then I would probably only include the Mu and Sigma values, since those are separated by playlist.

**Comment by Zod-** [comment]
They are not separat. It uses the [same value](https://gist.githubusercontent.com/Zod-/68d6285424fadc48b8cb/raw/69b17133f6efecb76a1971533726664241ea2e3d/skillmu) for all 4 playlists when searching a game. And the reason to include it isn't any different from the ranked values. You can get an idea of what level of skill to expect from the people in that match.

**Comment by trew** [comment]
Are you sure? Look at the Mu/Sigma values on the `RankPoints: ...` log rows. I'm pretty sure my Mu/Sigma values were vastly different in the unranked playlists.

**Comment by Zod-** [comment]
Did a quick test:

```
1v1
Search: Mu:42.102299 Sigma:2.500000
Loss:   Mu:41.9609   Sigma:2.4921

2v2
Search: Mu:41.960999 Sigma:2.500000
Loss:   Mu:41.9006   Sigma:2.4970

3v3:
Search: Mu:41.900501 Sigma:2.500000
Win:    Mu:41.9324   Sigma:2.4978
```

**Comment by trew** [comment]
I did a test too. Seems you are right. Unranked is a bunched up average of all the game modes. Damn that's lazy of them.

**Comment by trew** [comment]
Added in 1.0.1.
